### ISSUE TITLE
quartzfilter.py error

### ISSUE THREAD

**Issue by rxng** [benwiggy/PDFsuite#1]
Hi,

Am unable to use this one

`Traceback (most recent call last):
  File "quartzfilter.py", line 51, in <module>
    main(sys.argv[1:])
  File "quartzfilter.py", line 25, in main
    usage ()
NameError: global name 'usage' is not defined`

**Comment by benwiggy** [comment]
How are you calling it? You only get to that bit of code if the arguments are wrong.
quartzfilter.py filter input output

**Comment by benwiggy** [comment]
I've made some changes which may improve things.
