### ISSUE TITLE
Missing table of contents for second pdf after using pdf joiner

### ISSUE THREAD

**Issue by BhuvaneshBhatt** [benwiggy/PDFsuite#3]
Hi, I'm trying to join these two pdfs (the pdf with parts 1-4 comes first, naturally), but when I use your pdf joining tool, I cannot see the table of contents of the second pdf in the resulting Combined.pdf:
https://drive.google.com/open?id=1HMpDMmmepI870FqCaMgUmaKHNB2_22ts
https://drive.google.com/open?id=1juTWny43Ld1QFq6I-2h9FQzwdQUgQHpZ

**Comment by benwiggy** [comment]
It seems to work for me. Make sure you're using the latest script or the very new Quick Actions for Mojave.

<img width="332" alt="screenshot 6" src="https://user-images.githubusercontent.com/20556865/51864126-c1529180-233a-11e9-8625-7333ff3f1c5b.png">

**Comment by BhuvaneshBhatt** [comment]
Never mind. It was user error. Thanks for the quick reply!
