### ISSUE TITLE
Add svg/pdf logo into existing PDF?

### ISSUE THREAD

**Issue by adriel** [benwiggy/PDFsuite#4]
You mention in the readme "Add page numbers, watermarks, tints or other text and **graphics** to PDFs", but I don't see any further mention of adding images to a PDF.

I'm trying to replace an existing image with another in a PDF via the command line (even if that means placing the new image on top of the old one), but not sure if this is possible with PDFsuite?

**Comment by benwiggy** [comment]
The watermark PDF.py script will merge one PDF onto another one. It's in the PDF Services folder, as it's configured to 'stamp' the source image onto the PDF output of the print menu, (it was designed to create 'virtual headed paper'), but it could easily be reconfigured into a Quick Action or other script. 
The blend mode sets how the image interacts with the material underneath.

**Comment by adriel** [comment]
Hmmmm, thanks! I'll see if I can get it to work. (I have little experience in Python)
