### ISSUE TITLE
Error on export on some pdfs

### ISSUE THREAD

**Issue by M0rtenB** [benwiggy/PDFsuite#9]
I encounter some pdfs that cause trouble. I'm attaching one such. Using pdf2png.py I get the error `CoreGraphics PDF has logged an error. Set environment variable "CG_PDF_VERBOSE" to learn more.` The cover page is not exported.
I'm using Python 3.10.6, pyobjc 9.0.1, macOS Ventura 13.2.

[Ethnographic Sorcery (Chicago, 2007).pdf](https://github.com/benwiggy/PDFsuite/files/10787978/Ethnographic.Sorcery.Chicago.2007.pdf)

**Comment by benwiggy** [comment]
Setting the verbose flag gives me: "Object entry has invalid cross-reference generation number."

If I run the PDF through GhostScript, then the script works perfectly. That suggests a problem with the PDF itself.
